# Generated by Django 3.1.2 on 2020-12-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
