# Generated by Django 3.1.2 on 2020-12-28 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
        ('Blog', '0003_auto_20201229_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('e_mail', models.EmailField(help_text='vvedite po4tu', max_length=254)),
                ('avatar_user', models.ImageField(upload_to='avatar/')),
                ('event_user', models.ManyToManyField(to='Events.Event')),
                ('user_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.post')),
            ],
        ),
    ]
