# Generated by Django 3.1.2 on 2020-12-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
        ('Blog', '0005_auto_20201229_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='event_user',
            field=models.ManyToManyField(to='Events.Event'),
        ),
    ]
