# Generated by Django 3.1.2 on 2020-12-30 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_post_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_post', to='Blog.userblog'),
        ),
    ]
