# Generated by Django 3.1.2 on 2021-01-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20201230_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_post', to='Blog.userblog'),
        ),
    ]
